bundler_args: --without development
language: ruby
rvm:
  - rbx-19mode
  - jruby-19mode
  - jruby-head
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
notifications:
  email: false